### ISSUE TITLE
Is the EeasyPlayer-RTSP library free?

### ISSUE THREAD

**Issue by cristianilea-lateral** [EasyDSS/EasyPlayer-RTSP-iOS#12]
In the code there is this line:

`    int days = EasyRTSP_Activate("6D75724D7A502B32734B79414C6A78676E3850525176464659584E355547786865575679556C525455477858444661672F384C2F5A57467A65513D3D");
`

What happens when this key expires?

**Comment by SwordTTT** [comment]
if the key expires, the return value days<=0



&nbsp; 电话/微信：18221604428（同微信）
&nbsp; QQ：295222688
&nbsp; ***@***.***










&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tsingsee/EasyPlayer-RTSP-iOS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月31日(星期三) 晚上10:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[tsingsee/EasyPlayer-RTSP-iOS] Is the EeasyPlayer-RTSP library free? (#12)





 
In the code there is this line:
 
   int days = EasyRTSP_Activate("6D75724D7A502B32734B79414C6A78676E3850525176464659584E355547786865575679556C525455477858444661672F384C2F5A57467A65513D3D");
 
What happens when this key expires?

**Comment by cristianilea-lateral** [comment]
How do I get a new key?

**Comment by cristianilea-lateral** [comment]
Is there a way to get a new key? Or a key that never expires?

**Comment by 277oscar** [comment]
you can add my WeChat:18855117272
